name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update                                                                                                                                                                                                                                                                                                                                                             
          sudo apt install -y build-essential cmake libboost-all-dev default-jdk maven imagemagick                                                                                                                                                                                                                                                                                                     
          sudo apt install -y qt5-qmake libfmt-dev qtbase5-dev qtdeclarative5-dev qt5-image-formats-plugins libqt5svg5-dev                                                                                                                                                                                                                                                                

      - name: Configure CMake
        run: |
          mkdir -p build/Release                                                                                                                                                                                                                                                                                                                                                                     
          cd build/Release                                                                                                                                                                                                                                                                                                                                                                        
          cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_JAVA_LANGUAGE_PACKAGE=ON -DBUILD_PYTHON_LANGUAGE_PACKAGE=ON ../..

      - name: Build
        run: |
          cd build/Release                                                                                                                                                                                                                                                                                                                                                                       
          make Sourcetrail

      - name: Package
        run: |
          ./setup/Linux/createPackages.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Sourcetrail_Linux_64bit.tar.gz
          asset_name: Sourcetrail_Linux_64bit.tar.gz
          asset_content_type: application/gzip